<?php

namespace AppBundle\Repository;

/**
 * ExteriorFeaturesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExteriorFeaturesRepository extends \Doctrine\ORM\EntityRepository
{
}
