# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\UserEntity:
            algorithm: bcrypt

    providers:
        database_users:
            entity:
                class: AppBundle:UserEntity
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            anonymous: true
            stateless: true
            guard:
                authenticators:
                    - 'Username_Password_Authenticator'

        api:
            pattern: ^/api$
            anonymous: true
            stateless: true
            guard:
                authenticators:
                    - 'Jwt_Token_Authenticator'

        main:
            anonymous: ~
            pattern: ^/
            logout: true
            http_basic: ~
            provider: database_users