# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\Auth\UsersEntity:
            algorithm: bcrypt

    providers:
        database_users:
            entity:
                class: 'AppBundle\Entity\Auth\UsersEntity'
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/auth
            anonymous: true
            stateless: true
            guard:
                authenticators:
                    - 'Username_Password_Authenticator'

        registration:
            pattern: ^/api/user/activate
            anonymous: true
            security: false

        api:
            pattern: ^/api
            anonymous: false
            stateless: true
            guard:
                authenticators:
                    - 'Jwt_Token_Authenticator'

        main:
            pattern: ^/
            anonymous: ~
            provider: database_users

    access_control:
        - { path: ^/api, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path:  ^/api/user/activate, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }