# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    # Factories
    Api_Factory:
        class: AppBundle\Service\Vehicles\Api\SyncFactory
        arguments:
          - "%vehicle_api_type%"
          - "@doctrine.orm.entity_manager"

    # Services
    Sync_Abstract:
        class: AppBundle\Service\Vehicles\Api\SyncAbstract
        abstract: true
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
            - [syncApiVehiclesToDb, ['mfgs']]

    Nhtsa_Api:
        class: AppBundle\Service\Vehicles\Api\Nhtsa
        parent: Sync_Abstract

    Edmunds_Api:
        class: AppBundle\Service\Vehicles\Api\Edmunds
        parent: Sync_Abstract

    Sync_Api:
      class: AppBundle\Service\Vehicles\Api\SyncInterface
      factory: ["@Api_Factory", get]
      arguments:
          - "%vehicle_api_type%"
          - "@doctrine.orm.entity_manager"

    Sync_Db:
      class: AppBundle\Service\Vehicles\Api\SyncDb
      arguments: ["@doctrine.orm.entity_manager"]

    My_Vehicles:
        class: AppBundle\Service\Vehicles\MyVehicles
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@Sync_Db"