# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    User:
        class: AppBundle\Service\Auth\User
        arguments:
            - "@doctrine.orm.default_entity_manager"

    Jwt_Token_Authenticator:
        class: AppBundle\Security\JwtTokenAuthenticator
        arguments: ["@lexik_jwt_authentication.encoder.default", "@doctrine.orm.default_entity_manager"]

    Username_Password_Authenticator:
        class: AppBundle\Security\UsernamePasswordAuthenticator
        arguments: ["@security.password_encoder"]
        public: false

    # Sync Factory
    Api_Vehicles_Factory:
        class: AppBundle\Service\Vehicles\Api\ApiVehiclesFactory
        arguments: ["@doctrine.orm.vehicles_entity_manager", "%vehicle_api_type%"]

    # Sync Interface
    Api_Vehicles_Interface:
      class: AppBundle\Service\Vehicles\Api\ApiVehiclesInterface
      factory: ["@Api_Vehicles_Factory", get]
      arguments: ["@doctrine.orm.vehicles_entity_manager", "%vehicle_api_type%"]

    # Api Vehicles Service
    Api_Vehicles:
        class: AppBundle\Service\Vehicles\Api\ApiVehicles
        arguments: ["@doctrine.orm.vehicles_entity_manager"]

    # Vehicles Service
    Vehicles:
        class: AppBundle\Service\Vehicles\Vehicles
        arguments: ["@doctrine.orm.vehicles_entity_manager", "@Api_Vehicles", "@File_Uploader"]

    Assets:
        class: AppBundle\Service\Vehicles\Assets
        arguments: ["@doctrine.orm.vehicles_entity_manager", "@File_Uploader"]

    Rooms:
        class: AppBundle\Service\Properties\Rooms
        arguments: ["@doctrine.orm.houses_entity_manager"]

    Features:
        class: AppBundle\Service\Properties\Features
        arguments: ["@doctrine.orm.houses_entity_manager"]

    Exterior_Features:
        class: AppBundle\Service\Properties\ExteriorFeatures
        arguments: ["@doctrine.orm.houses_entity_manager"]

    Interior_Features:
        class: AppBundle\Service\Properties\InteriorFeatures
        arguments: ["@doctrine.orm.houses_entity_manager"]

    Configured_Rooms:
        class: AppBundle\Service\Configuration\Properties\Rooms

    Properties:
        class: AppBundle\Service\Properties\Properties
        arguments: ["@doctrine.orm.houses_entity_manager", "@Configured_Rooms", "@File_Uploader"]

    Paints:
        class: AppBundle\Service\Paints\Paints
        arguments: ["@doctrine.orm.houses_entity_manager"]

    File_Uploader:
        class: AppBundle\Service\FileUploader
        arguments: ["%assets_dir%"]