# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    User:
        class: AppBundle\Service\Users\User
        arguments:
            - "@doctrine.orm.entity_manager"

    Jwt_Token_Authenticator:
        class: AppBundle\Security\JwtTokenAuthenticator
        arguments: ["@lexik_jwt_authentication.encoder.default", "@doctrine.orm.entity_manager"]

    Username_Password_Authenticator:
        class: AppBundle\Security\UsernamePasswordAuthenticator
        arguments: ["@security.password_encoder"]
        public: false

    # Factories
    Sync_Factory:
        class: AppBundle\Service\Vehicles\Api\SyncFactory
        arguments: ["@doctrine.orm.vehicles_entity_manager", "%vehicle_api_type%"]

    # Services
    Sync_Abstract:
        class: AppBundle\Service\Vehicles\Api\SyncAbstract
        abstract: true
        arguments: ["@doctrine.orm.vehicles_entity_manager"]
        calls:
            - [syncApiVehiclesToDb, ['mfgs']]

    Nhtsa_Api:
        class: AppBundle\Service\Vehicles\Api\Nhtsa
        parent: Sync_Abstract

    Edmunds_Api:
        class: AppBundle\Service\Vehicles\Api\Edmunds
        parent: Sync_Abstract

    Sync_Api:
      class: AppBundle\Service\Vehicles\Api\SyncInterface
      factory: ["@Sync_Factory", get]
      arguments: ["@doctrine.orm.vehicles_entity_manager", "%vehicle_api_type%"]

    Sync_Db:
      class: AppBundle\Service\Vehicles\Api\SyncDb
      arguments: ["@doctrine.orm.vehicles_entity_manager"]

    File_Uploader:
        class: AppBundle\Service\FileUploader
        arguments: ["%assets_dir%"]

    Assets:
        class: AppBundle\Service\Assets
        arguments: ["@doctrine.orm.entity_manager", "@File_Uploader"]

    My_Vehicles:
        class: AppBundle\Service\Vehicles\MyVehicles
        arguments: ["@doctrine.orm.vehicles_entity_manager", "@Sync_Db", "@File_Uploader"]