# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    # Authenticator
    Jwt_Token_Authenticator:
        class: AppBundle\Security\JwtTokenAuthenticator
        arguments: ["@doctrine.orm.default_entity_manager", "@lexik_jwt_authentication.encoder.default"]

    # Authenticator
    Username_Password_Authenticator:
        class: AppBundle\Security\UsernamePasswordAuthenticator
        arguments: ["@security.password_encoder"]

    # Users
    Users:
        class: AppBundle\Service\Auth\Users
        arguments: ["@doctrine.orm.default_entity_manager"]

    # Email
    Email:
        class: AppBundle\Service\Email\SwiftMessage
        arguments: ["@mailer", "@twig"]

    # Sync Factory
    Manufacturers_Factory:
        class: AppBundle\Service\Vehicles\Api\ManufacturersFactory
        arguments: ["@doctrine.orm.vehicles_entity_manager", "%vehicle_api_type%"]

    # Sync Interface
    Manufacturers_Interface:
      class: AppBundle\Service\Vehicles\Api\ManufacturersInterface
      factory: ["@Manufacturers_Factory", get]
      arguments: ["@doctrine.orm.vehicles_entity_manager", "%vehicle_api_type%"]

    # Api Vehicles Service
    Manufacturers:
        class: AppBundle\Service\Vehicles\Api\Manufacturers
        arguments: ["@doctrine.orm.vehicles_entity_manager"]

    # Vehicles Service
    Vehicles:
        class: AppBundle\Service\Vehicles\Vehicles
        arguments: ["@doctrine.orm.vehicles_entity_manager", "@Manufacturers", "@File_Uploader"]

    Assets:
        class: AppBundle\Service\Vehicles\Assets
        arguments: ["@doctrine.orm.vehicles_entity_manager", "@File_Uploader"]

    Rooms:
        class: AppBundle\Service\Properties\Rooms
        arguments: ["@doctrine.orm.houses_entity_manager"]

    Features:
        class: AppBundle\Service\Properties\Features
        arguments: ["@doctrine.orm.houses_entity_manager"]

    Exterior_Features:
        class: AppBundle\Service\Properties\ExteriorFeatures
        arguments: ["@doctrine.orm.houses_entity_manager"]

    Interior_Features:
        class: AppBundle\Service\Properties\InteriorFeatures
        arguments: ["@doctrine.orm.houses_entity_manager"]

    Configured_Rooms:
        class: AppBundle\Service\Configuration\Properties\Rooms

    Properties:
        class: AppBundle\Service\Properties\Properties
        arguments: ["@doctrine.orm.houses_entity_manager", "@Configured_Rooms", "@File_Uploader"]

    Paints:
        class: AppBundle\Service\Paints\Paints
        arguments: ["@doctrine.orm.houses_entity_manager"]

    Vendors:
        class: AppBundle\Service\Vendors\Vendors
        arguments: ["@doctrine.orm.houses_entity_manager"]

    Vendor_Categories:
        class: AppBundle\Service\Vendors\VendorCategories
        arguments: ["@doctrine.orm.houses_entity_manager"]

    File_Uploader:
        class: AppBundle\Service\FileUploader
        arguments: ["%assets_dir%"]